collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true # automatically set is_post=true for all posts (used to determine in which header to show at the top of each page)
      image: default
  - scope:
      path: ""
    values:
      layout: "default"

# Tags (This tells Jekyll to generate a new directory called tag and place tag pages in that directory.)
tag_page_dir: tag

timezone: America/Denver
