collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true # automatically set is_post=true for all posts (used to determine in the default layout which header to show)
- scope:
      path: ""
    values:
      layout: "default"
      
timezone: America/Denver
